import { ArrowLeft } from "lucide-react";
import Link from "next/link";

export const metadata = {
  title: "Terms of Service — OneSite",
};

export default function TermsOfService() {
  return (
    <div className="min-h-screen px-6 py-32">
      <div className="max-w-3xl mx-auto">
        <Link
          href="/"
          className="inline-flex items-center gap-2 text-sm text-zinc-400 hover:text-white transition mb-12"
        >
          <ArrowLeft className="w-4 h-4" />
          Back to OneSite
        </Link>

        <h1 className="text-3xl md:text-4xl font-bold mb-8">Terms of Service</h1>

        <div className="prose prose-invert prose-zinc max-w-none space-y-6 text-sm text-zinc-400 leading-relaxed">
          <p>
            <strong className="text-zinc-200">Last updated:</strong> June 2025
          </p>

          <h2 className="text-xl font-semibold text-zinc-200 mt-8">1. Service Overview</h2>
          <p>
            OneSite is an AI-powered website generation platform. By using OneSite, you agree to these terms.
            We provide AI-generated website code that is deployed to your own Vercel account.
          </p>

          <h2 className="text-xl font-semibold text-zinc-200 mt-8">2. Subscription & Billing</h2>
          <p>
            Subscriptions are billed through Stripe. All plans include a 7-day free trial. Unused AI credits
            do not roll over. You can cancel anytime; your deployed sites remain live on your Vercel account.
          </p>

          <h2 className="text-xl font-semibold text-zinc-200 mt-8">3. Code Ownership</h2>
          <p>
            You own all code generated by OneSite. You may export, modify, and redistribute it freely.
            OneSite does not claim any ownership or license over your generated code.
          </p>

          <h2 className="text-xl font-semibold text-zinc-200 mt-8">4. Acceptable Use</h2>
          <p>
            You agree not to use OneSite to generate illegal content, phishing sites, or material that
            infringes on third-party rights. We reserve the right to terminate accounts that violate
            these terms.
          </p>

          <h2 className="text-xl font-semibold text-zinc-200 mt-8">5. Limitation of Liability</h2>
          <p>
            OneSite is provided &quot;as is&quot;. We do not guarantee that generated code will be error-free or
            suitable for any particular purpose. Users are responsible for reviewing generated code
            before deployment.
          </p>

          <h2 className="text-xl font-semibold text-zinc-200 mt-8">6. Contact</h2>
          <p>
            Questions about these terms?{" "}
            <a href="mailto:support@onesite.iclouds.work" className="text-violet-400 hover:text-violet-300">
              support@onesite.iclouds.work
            </a>
          </p>
        </div>
      </div>
    </div>
  );
}
